### ISSUE TITLE
Login form: access denied

### ISSUE THREAD

**Issue by dimitarsp** [getgrav/grav-skeleton-landio-site#11]
Trying to understand the functionality of the login incorporation in the menu. When I try to login myself, or another test user in a just-installed skeleton, i get the following:
`Access Denied...`

**Comment by rhukster** [comment]
What steps did you perform?  Did you setup an `access:` attribute on the page like this:

```
access:
    site.login: true
```

Did you install the login plugin?  Did you get prompted for a username/password? If so does the user have the correct `site.login` access defined in it's account.yaml?

**Comment by dimitarsp** [comment]
- I downloaded the skeleton version from getgrav.org, which comes with login plugin
- I loaded it locally and it asked me to create an admin user
- I checked the user.yaml and `site.login` is defined as `true`

I am not sure where to put 
```
access: 
   site.login: true
```

Here the login.md as provided by the skeleton:

```
---
title: User Login
slug: user-login
navbar_class: navbar-dark bg-inverse


form:
  name: login
  action:
  method: post

  fields:
      - name: username
        id: username
        type: text
        placeholder: Username
        autofocus: true
        classes: form-control form-control-lg

      - name: password
        id: password
        type: password
        placeholder: Password  
        classes: form-control form-control-lg

---

```
